---
layout: post
title: Assert.Throws<> Over ExpectedException
date: 2013-10-09 04:39:36.000000000 +02:00
categories:
- .Net framework
- TDD
tags: []
status: publish
type: post
published: true
meta:
  _edit_last: '1'
author:
  login: admin
  email: mads.toustrup@gmail.com
  display_name: admin
  first_name: ''
  last_name: ''
---
<p>Writing unit tests that expects a given type of exception under given circumstances is essential for any test suite. Although it is useful to use the correct assertion types when testing for exceptions. In this post I will provide some guidance on why to use Assert.Throws&lt;&gt;() instead of ExpectedException.</p>
<p>Using the ExpectedException:</p>
<div id="scid:9ce6104f-a9aa-4a17-a79f-3a39532ebf7c:732f249e-7f06-4e8d-b37c-567d5c737d39" class="wlWriterEditableSmartContent" style="float: none; margin: 0px; display: inline; padding: 0px;">
<div style="border: #000080 1px solid; color: #000; font-family: 'Courier New', Courier, Monospace; font-size: 10pt;">
<div style="background: #ddd; overflow: auto;">
<ol style="background: #ffffff; margin: 0 0 0 2.5em; padding: 0 0 0 5px;" start="1">
<li><span style="background: #ffffff; color: #808080;">///&lt;summary&gt;</span></li>
<li style="background: #f3f3f3;"><span style="background: #ffffff; color: #808080;">///</span><span style="background: #ffffff; color: #008000;"> Testing exception handling</span></li>
<li><span style="background: #ffffff; color: #808080;">///&lt;/summary&gt;</span></li>
<li style="background: #f3f3f3;"><span style="background: #ffffff; color: #000000;">[</span><span style="background: #ffffff; color: #2b91af;">Test</span><span style="background: #ffffff; color: #000000;">]</span></li>
<li><span style="background: #ffffff; color: #000000;">[</span><span style="background: #ffffff; color: #2b91af;">ExpectedException</span><span style="background: #ffffff; color: #000000;">(</span><span style="background: #ffffff; color: #0000ff;">typeof</span><span style="background: #ffffff; color: #000000;">(</span><span style="background: #ffffff; color: #2b91af;">ArgumentNullException</span><span style="background: #ffffff; color: #000000;">))]</span></li>
<li style="background: #f3f3f3;"><span style="background: #ffffff; color: #0000ff;">public</span><span style="background: #ffffff; color: #0000ff;">void</span><span style="background: #ffffff; color: #000000;"> WhateverTestName()</span></li>
<li><span style="background: #ffffff; color: #000000;">{</span></li>
<li style="background: #f3f3f3;">    <span style="background: #ffffff; color: #008000;">// Arrange</span></li>
<li>    <span style="background: #ffffff; color: #0000ff;">var</span><span style="background: #ffffff; color: #000000;"> sut = </span><span style="background: #ffffff; color: #0000ff;">new</span><span style="background: #ffffff; color: #2b91af;">SystemUnderTest</span><span style="background: #ffffff; color: #000000;">();</span></li>
<li style="background: #f3f3f3;"></li>
<li>    <span style="background: #ffffff; color: #008000;">// Act</span></li>
<li style="background: #f3f3f3;">    <span style="background: #ffffff; color: #008000;">// Assert</span></li>
<li>    <span style="background: #ffffff; color: #000000;">sut.MethodThatThrowsEception();</span></li>
<li style="background: #f3f3f3;"><span style="background: #ffffff; color: #000000;">}</span></li>
</ol>
</div>
</div>
</div>
<p>&nbsp;</p>
<p>In the above example whenever / wherever an exception of the given type is thrown inside the test, the test is considered passed.</p>
<p>A refactored example:</p>
<div id="scid:9ce6104f-a9aa-4a17-a79f-3a39532ebf7c:3a0c3937-0ef8-4590-9d67-f98ffb6c9ac5" class="wlWriterEditableSmartContent" style="float: none; margin: 0px; display: inline; padding: 0px;">
<div style="border: #000080 1px solid; color: #000; font-family: 'Courier New', Courier, Monospace; font-size: 10pt;">
<div style="background: #ddd; overflow: auto;">
<ol style="background: #ffffff; margin: 0 0 0 2.5em; padding: 0 0 0 5px;" start="1">
<li><span style="background: #ffffff; color: #808080;">///&lt;summary&gt;</span></li>
<li style="background: #f3f3f3;"><span style="background: #ffffff; color: #808080;">///</span><span style="background: #ffffff; color: #008000;"> Testing exception handling</span></li>
<li><span style="background: #ffffff; color: #808080;">///&lt;/summary&gt;</span></li>
<li style="background: #f3f3f3;"><span style="background: #ffffff; color: #000000;">[</span><span style="background: #ffffff; color: #2b91af;">Test</span><span style="background: #ffffff; color: #000000;">]</span></li>
<li><span style="background: #ffffff; color: #0000ff;">public</span><span style="background: #ffffff; color: #0000ff;">void</span><span style="background: #ffffff; color: #000000;"> WhateverTestName()</span></li>
<li style="background: #f3f3f3;"><span style="background: #ffffff; color: #000000;">{</span></li>
<li>    <span style="background: #ffffff; color: #008000;">// Arrange</span></li>
<li style="background: #f3f3f3;">    <span style="background: #ffffff; color: #0000ff;">var</span><span style="background: #ffffff; color: #000000;"> sut = </span><span style="background: #ffffff; color: #0000ff;">new</span><span style="background: #ffffff; color: #2b91af;">SystemUnderTest</span><span style="background: #ffffff; color: #000000;">();</span></li>
<li></li>
<li style="background: #f3f3f3;">    <span style="background: #ffffff; color: #008000;">// Act</span></li>
<li>    <span style="background: #ffffff; color: #008000;">// Assert</span></li>
<li style="background: #f3f3f3;">    <span style="background: #ffffff; color: #2b91af;">Assert</span><span style="background: #ffffff; color: #000000;">.Throws&lt;</span><span style="background: #ffffff; color: #2b91af;">ArgumentNullException</span><span style="background: #ffffff; color: #000000;">&gt;(() =&gt; sut.MethodThatThrowsEception());</span></li>
<li><span style="background: #ffffff; color: #000000;">}</span></li>
</ol>
</div>
</div>
</div>
<p>&nbsp;</p>
<p>Now, instead of using the ExpectedException, I use Assert.Throws&lt;&gt;(). This provides a number of benefits / advantages:</p>
<ul>
<li>Readability
<ul>
<li>The test is now more readable, the reader is not in doubt of where in the code the exception is expected to be thrown. Furthermore, the ExpectedException attribute is easily overseen, which makes it difficult to understand what the intent of the test is.</li>
</ul>
</li>
<li>Multiple conditions
<ul>
<li>It is possible to test other conditions. Using the ExpectedException you cannot test anything else than the whether the exception is thrown.</li>
</ul>
</li>
<li>Possible false expectation
<ul>
<li>Setting the ExpectedException on a test case, makes it open to be passed whenever an exception of the given type is thrown inside the test. This could lead to some serious and unforeseen side-effects.</li>
</ul>
</li>
</ul>
